// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hocujulbxxdobcwmakvc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhvY3VqdWxieHhkb2Jjd21ha3ZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MjMxODUsImV4cCI6MjA2NTQ5OTE4NX0.ToQ564L-kQfd-vpvMmjOBgy5DqwNwrV48Or4C3p4nE4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);